[Interface]
Address = 192.168.1.2/32
PrivateKey = mBloANBDB0zKITy5/hEcPeZ4cTkKuxWBPD67Ioer5kY=
DNS = 192.168.1.1

[Peer]
PublicKey = KDnXlX/dJlpEOxX3ENdTeYuTO5FHRvY4KuwO9CG3dVw=
PresharedKey = pihZn/RiQ7J7bATb934r3Cpa1xlsmHCctdl70YaY3pI=
Endpoint = 141.76.46.220:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
