[Interface]
Address = 192.168.1.1/24
ListenPort = 51820
PrivateKey = KEu27buPo0kK4l+5EtMPOk/BQN6HAkBg0nHZkyOCTWw=

[Peer]
PublicKey = 98ds9ghhibXIxSdBPucJeUJK3z3MVly8AamAJAXQPzg=c
PresharedKey = pihZn/RiQ7J7bATb934r3Cpa1xlsmHCctdl70YaY3pI=
AllowedIPs = 192.168.1.2/32
