# bind to LAN interface only
bind-dynamic
interface=<lan>
except-interface=lo

# do not read /etc/hosts
no-hosts

# forward Fully Qualified Domain Names only (excluding hostnames)
domain-needed

# do not forward reverse lookups for private IP address
bogus-priv

# do not cache failed lookups to avoid storing error results due to network fluctuations
no-negcache

# act as the authoritative DHCP server to speed up network configuration for devices in the LAN
dhcp-authoritative

# specify DHCP range
dhcp-range=192.168.0.100,192.168.0.254

# accelerate LAN access to the web server
host-record=netseclab1.inf.tu-dresden.de,192.168.0.3
