# clean all existing rulesets
flush ruleset

define wan_if     = <wan>
define lan_if     = <lan>
define wan_ip     = 141.76.46.220
define lan_ip     = 192.168.0.1
define lan_net    = 192.168.0.0/24

table ip nat {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
    }

    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;

        # NAT for LAN
        oifname $wan_if ip saddr $lan_net snat to $wan_ip
    }
}

table ip filter {
    chain forward {
        # default forwarding policy is DROP
        type filter hook forward priority filter; policy drop;

        # drop packets of invalid connections
        ct state invalid drop

        # accept all established and related connections
        ct state { established, related } accept

        # prevent source IP address spoofing
        iifname $wan_if ip saddr $lan_net drop

        # reject HTTP/3 requests because squid can not handle it
        iifname $lan_if ip saddr $lan_net udp dport 443 reject

        # allow LAN clients to initiate connections to any public network device
        iifname $lan_if oifname $wan_if ip saddr $lan_net accept

        # accept port-forwarded traffic
        ct status dnat accept
    }

    chain input {
        # default input policy is DROP
        type filter hook input priority filter; policy drop;

        # drop packets of invalid connections
        ct state invalid drop

        # accept all established and related connections
        ct state { established, related } accept

        # accept loopback traffic
        iifname lo accept

        # accept ICMP packets
        ip protocol icmp accept

        # prevent source IP address spoofing
        iifname $wan_if ip saddr $lan_net drop

        # accept redirected traffic
        ct status dnat accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

include "/etc/nftables.d/*.nft"
