http_port 3128 intercept
# Since we are only peeking at the SNI without acting as a TLS man-in-the-middle,
# generate-host-certificates can be set to off.
# This also eliminates the need to configure sslcrtd_program.
https_port 3129 intercept ssl-bump generate-host-certificates=off cert=/etc/squid/ca.pem

# peek at the SNI
acl step1 at_step SslBump1
ssl_bump peek step1
ssl_bump splice all

# allow all traffic by default
http_access allow all
